[package]
name = "empty-hardware"
version = "0.1.0"
authors = ["mayrom <nhruo123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gameboy_core = { path = "../gameboy_core" }